### ISSUE TITLE
downloader getting stuck

### ISSUE THREAD

**Issue by nocoel** [Jules-WinnfieldX/CyberDropDownloader#137]
so here i ran it again and as i described in the other issue it is behaving the same way, it got stuck (for about 30min) at this point: https://imgur.com/a/tyqS087
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/8680721/downloader.log)
i also want to note that it doesn't get stuck on smaller thread, it does finish them, the thread mentioned above is pretty big

and about the messy display while checking existing files, i really don't remember when and how i could have activated such a "debug mode", moreover i went and tried older versions and cyberdrop-dl 2.20.1 gave me the intended display as shown here (https://imgur.com/a/IyKGTEG) although it creates duplicates which was fixed in recent versions
i also found that this "debug mode" display starts with 2.20.2, at least in my end, is no one else experiencing that?

**Comment by Jules-WinnfieldX** [comment]
I put up 2.20.7. See if that solves the neat-ness. But yes. Re-run it, and just let it go, even if it gets stuck

**Comment by Jules-WinnfieldX** [comment]
So. I was looking at the wrong log statement. That one for neat-ness is fixed in 2.20.8

**Comment by nocoel** [comment]
> I put up 2.20.7. See if that solves the neat-ness. But yes. Re-run it, and just let it go, even if it gets stuck

i launched i re-run with 2.20.7 the neat-ness is half fixed (it began neaty then i returned to the old messy way), on bright side it bypassed the point it usually gets stuck at, and it looks like it's gonna finish fingers crossed.
once this ends i'll try another one with 2.20.8 and report back

**Comment by nocoel** [comment]
so the messy display is gone when it finds `file already exists and matches expected size`

but it is still present when it fails to download a file with `Error attempting Image.jpg: See downloader.log for details`

and a new problem (2.20.8) is that it is failling a lot of downloads that it were not failing before
this is how it looks: https://youtu.be/PqbooyppKhI

and finally it still does gets stuck (it got stuck in the last line seen in the video)after checking the downloader.log it appears it got stuck on a dead link though

[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/8682765/downloader.log)

**Comment by Jules-WinnfieldX** [comment]
> so the messy display is gone when it finds `file already exists and matches expected size`
> 
> but it is still present when it fails to download a file with `Error attempting Image.jpg: See downloader.log for details`
> 
> and a new problem (2.20.8) is that it is failling a lot of downloads that it were not failing before this is how it looks: https://youtu.be/PqbooyppKhI
> 
> and finally it still does gets stuck (it got stuck in the last line seen in the video)after checking the downloader.log it appears it got stuck on a dead link though
> 
> [downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/8682765/downloader.log)

The "see downloader.log for details" is by design. If a file fails, the user should know something went wrong

As for the getting "stuck" on dead links, that should be resolved. As is the error attempting messages you are seeing. (Version # 2.21.3)

**Comment by nocoel** [comment]
it ran and finished as smoothly as it used to, thank you for this!!
it's amazing how fast you get back with fixes and sorry for dumping a problem after another

**Comment by Jules-WinnfieldX** [comment]
All good, I want it to run smoothly just as much as you. Had some free time today.
