### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by umpanz** [Jules-WinnfieldX/CyberDropDownloader#331]
After updating pip (since the downloader asked me to) the program doesn't work anymore. It worked before that without any problem, I'm using Python 3.11.1 tho, could that be the reason?

```
C:\Users\Name\Desktop\Cyberdrop_DL.V3>cyberdrop-dl
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python\Python311\Scripts\cyberdrop-dl.exe\__main__.py", line 7, in <module>
  File "C:\Python\Python311\Lib\site-packages\cyberdrop_dl\main.py", line 222, in main
    args = run_args(args.config_file, argparse.Namespace(**vars(args)).__dict__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\site-packages\cyberdrop_dl\base_functions\config_manager.py", line 96, in run_args
    create_config(config, cmd_arg)
  File "C:\Python\Python311\Lib\site-packages\cyberdrop_dl\base_functions\config_manager.py", line 16, in create_config
    validate_config(config)
  File "C:\Python\Python311\Lib\site-packages\cyberdrop_dl\base_functions\config_manager.py", line 54, in validate_config
    data = yaml.load(yamlfile, Loader=yaml.FullLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\site-packages\yaml\constructor.py", line 51, in get_single_data
    return self.construct_document(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\site-packages\yaml\constructor.py", line 60, in construct_document
    for dummy in generator:
  File "C:\Python\Python311\Lib\site-packages\yaml\constructor.py", line 413, in construct_yaml_map
    value = self.construct_mapping(node)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\site-packages\yaml\constructor.py", line 218, in construct_mapping
    return super().construct_mapping(node, deep=deep)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\site-packages\yaml\constructor.py", line 143, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\site-packages\yaml\constructor.py", line 100, in construct_object
    data = constructor(self, node)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\site-packages\yaml\constructor.py", line 427, in construct_undefined
    raise ConstructorError(None, None,
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object/apply:pathlib.WindowsPath'
  in "config.yaml", line 60, column 23
```

**Comment by umbraburn21** [comment]
Yeah exact same thing is happening to me. Thought it was a problem on my end.

**Comment by premium9000** [comment]
stopped working for me as well. sad.

**Comment by Jules-WinnfieldX** [comment]
Can I see what's in your config? (take out passwords first if they are in there)

**Comment by Jules-WinnfieldX** [comment]
NVM this is fixed in the latest version.

**Comment by umbraburn21** [comment]
Still getting this error after the recent update.
Starting Cyberdrop-DL
We are running version 4.0.4 of Cyberdrop Downloader
Starting Scrape
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\casht\AppData\Local\Programs\Python\Python311\Scripts\cyberdrop-dl.exe\__main__.py", line 7, in <module>
  File "C:\Users\casht\AppData\Local\Programs\Python\Python311\Lib\site-packages\cyberdrop_dl\main.py", line 233, in main
    loop.run_until_complete(director(args, links))
  File "C:\Users\casht\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\casht\AppData\Local\Programs\Python\Python311\Lib\site-packages\cyberdrop_dl\main.py", line 185, in director
    Cascade, Forums = await scrape_links(Scraper, links)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\casht\AppData\Local\Programs\Python\Python311\Lib\site-packages\cyberdrop_dl\main.py", line 156, in scrape_links
    await asyncio.wait(tasks)
  File "C:\Users\casht\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 415, in wait
    raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.
sys:1: RuntimeWarning: coroutine 'ScrapeMapper.map_url' was never awaited

C:\Users\casht\Downloads\Compressed\Cyberdrop_DL.V3>pause
Press any key to continue . . .
