### ISSUE TITLE
[BUG] Primary keys (?) error after updating to V5.1.92

### ISSUE THREAD

**Issue by asdf1151** [Jules-WinnfieldX/CyberDropDownloader#838]
After updating to python3.11 and V5.1.92, I was able to start up cyberdrop-dl but when I hit download, I run into "Fixing primary keys in the database: DO NOT EXIT THE PROGRAM" error and the last line of the traceback is "sqlite3.OperationalError: table media_copy has 8 columns but 7 values were supplied"

Is this an issue with my installation of python 3.11 or is there another problem?

**Comment by Jules-WinnfieldX** [comment]
5.1.93 going up now should fix that.

**Comment by asdf1151** [comment]
Thanks for the quick response. I've updated to 5.1.93 just now via pip install but still getting an error. Final line from the traceback is a slight variation:

"sqlite3.OperationalError: 7 values for 8 columns"

**Comment by Jules-WinnfieldX** [comment]
can I see the full traceback?

**Comment by asdf1151** [comment]
Great! I'll give it a shot later. Thanks again for the quick fixes!
