### ISSUE TITLE
[FEATURE] Improve handling of 418/500 on imgur.com

### ISSUE THREAD

**Issue by baccccccc** [Jules-WinnfieldX/CyberDropDownloader#876]
note: I filed a bunch of similar issues recently. In all those cases, I was more confident about what actually went on. Here I might have no idea. But I still wish we could improve that.

here's a few imgur.com links
```
https://imgur.com/download/Qe2YKRV, 418 - No content-type in response header
https://imgur.com/download/MQ3OmCS, 418 - No content-type in response header
https://imgur.com/download/ud8GcuB, 418 - No content-type in response header
https://imgur.com/download/63ddiQW, 418 - No content-type in response header
https://imgur.com/download/LedZSQT, 418 - No content-type in response header
https://imgur.com/download/jl8RNqk, 418 - No content-type in response header
https://imgur.com/download/ssvDfai, 418 - No content-type in response header
https://imgur.com/download/zNZA8vs, 418 - No content-type in response header
https://imgur.com/download/vqgN6qs, 418 - No content-type in response header
```

so, to CDL it looks like a 418. But if you check it with a browser, you might get a different picture. YMMV but what I get looks like a JSON with a 500 error. (Although I'd argue it should have been a 503.)
```
{
    "data": {
        "error": "Imgur is temporarily over capacity. Please try again later."
    },
    "success": false,
    "status": 500
}
```

So, this is where I get confused. Did CDL receive the same JSON but could not parse it correctly (because, naturally, there's no content-type in this response)? In this case it should be a relatively straightforward fix. We just need to learn how to handle this JSON.

Or did it _in fact_ get a 418 but browser gets a different response? Then it might become tricky. But either way, probably some room for improvement.

**Comment by Jules-WinnfieldX** [comment]
If you google 418 you'll realize it's a "joke" status. 

I assign it when it says, in cases where there is no content-type in the response header from the server. To connect it to the pixeldrain issue, think mime-type. 

From that URL CDL is expecting image/jpg mime-type but isn't receiving anything, so it fails out with a 418. 

I could add another *special* case for this, but I'll do it later.

**Comment by baccccccc** [comment]
yeh, I'm aware of the joke, but I thought that maybe imgur returns it because they consider it too much of a corner case to bother with an actual status. (Or maybe they'd want to be intentionally vague about this one file. You never know...)

but I'd say it probably deserves _special case_ handling on CDL side because these seem to be quite widespread. I have no idea how permanent the error is. I.e., based on the description they provide, I'd expect it to be transient and be gone after a few retries within an hour or so. But apparently they are quite sticky.

who knows, maybe they're masking a 404 or something like a 451 with this message. So, while handling this case more precisely won't _ultimately_ solve the problem, at least it'll make it easier to troubleshoot on the user side.

think of it like this. When I'm going through my Download_Error_URLs, if I see a 418 I get worried and want to investigate. If I see a 500 I go _"meh"_ and it saves me a bunch of time.

**Comment by Jules-WinnfieldX** [comment]
5.2.29 should fix this.

**Comment by baccccccc** [comment]
Sorry, does not look like it's fixed. I still get that JSON from Imgur (example: `https://imgur.com/download/H7aoqwq`). But CDL 5.2.31 interprets that as
```
ERROR    : 2024-04-15 15:37:42,596 : utilities.py:103 : Download failed: https://imgur.com/download/H7aoqwq with status 418 and message No content-type in response header
```

**Comment by Jules-WinnfieldX** [comment]
Unsure why the download link is reporting 500. But the actual API is reporting 404. Fixing the link and going to where that image should be also returns a 404. I'm going with it's dead links and a bad JSON response.
